### ISSUE TITLE
Is this application 'complete' or dead?

### ISSUE THREAD

**Issue by gurufordy** [AutoScout24/FeatureBee#73]
Hi,

I'm looking to use or write something like this and see that this product hasn't been released since 2014. Is it feature complete or is it just abandoned?

/Matt

**Comment by algra** [comment]
This application is used in our production, so it's production ready and can be used by anyone else as well. Because of different reasons it was decided to not do any further development in this application on our side, but any contributions are very welcome.

Despite of that, there is another application, https://github.com/AutoScout24/dimmer, which is going to be developed in another technology (Scala & Docker instead of C#) next weeks / months and from feature point of view, it should be seen as next major version of FeatureBee.

**Comment by NicoJuicy** [comment]
What are the main differences with dimmer / toguru ?

I see the following:
- Tags
- Simpler on/off switch
- How is the rollout % implemented? Is this a % of every request that the rollout is enabled?
- I see Authorization headers are used?

I do think the implementation of toguru is probably cleaner. The jquery UI layout ( just executed it) feels sluggish and isn't really usefull for large features.

What have you learned from this project and what have you learned from dimmer / toguru?

PS. Nice work on both projects though. 
I noticed another bug on the creation of jquery UI dialog, but this is probably due to versions or something else ( while running this project). I suppose this project isn't used anymore in production?

**Comment by algra** [comment]
@NicoJuicy FeatureBee is considered as "stable", but not abandonned, means it is still used in production in .NET part of our platform. As I wrote in my previous comment, we decided to not do any development on our side mainly because of changing our tech-stack completely to Scala / AWS, but we will be happy to accept any contributions from open-source community.

Toguru is more or less superseder of FeatureBee, with learnings we got from working with FeatureBee, but designed to run in our new tech stack, e.g. Scala / Docker, from the beginning.

* **Tags**: at the moment these in toguru are just labels, without any logic behind. Attributes in toguru are conditions in FeatureBee, but you have to specify which attributes to use in code: https://github.com/AutoScout24/toguru-scala-client#custom-client-attributes, this way it's not that transparent for the usage, but very flexible.
* **On/off**: currently, when people are reasoning about toggles in their blog posts (e.g. https://martinfowler.com/articles/feature-toggles.html), usually it's differented between 3 types of toggles:
    * **rollout toggles**: Used to canary release features, starting with very small amount of traffic and ending up with 100%, these should exist until feature is 100% rolled out and should be deleted afterwards. Since it's most used scenario in our daily work, we started with implementation of these, but on/off was not show-stopper for us, mainly, because you can mimic on/off behaviour with setting percentage to 0 and back.
    * **ops toggles**: In most cases used for emergencies, like disabling some features, e.g. integration of some 3rd party systems if they're down, these usually are long living and having same lifecycle as feature in  production. This is exactly where you need on/off behaviour, it's just not there yet, but for sure will come at some point.
    * **multivariant toggles**: Usually used for multivariant A/B/... testing, where you split some amount of traffic between multiple versions and measure which one performs better. For now with toguru you can mimic 3 versions behaviour by defining two toggles with 33 and 66% rollout respectively and then do checks something like _if toggle1.enabled and toggle2.enabled then variant1 else if toggle1.disabled and toggle2.enabled then variant2 else variant3_. I know, it looks like ugly workaround, but unfortunately this way of using toggles is not on our radar at the moment, so, there is no explicit implementation for this. If you need it and want to contribute, feel free to create an issue in toguru repo to start discussion about it.
* **Distribution**: every user should have a user ID (UUID actually) cookie which is used for % calculations to understand if toggle is switched on or off based on percentage, or random UUID will be used if none is set. For better understanding of logic in toguru, this could be a good start: https://github.com/AutoScout24/toguru-scala-client/blob/master/src/main/scala/toguru/impl/Conditions.scala, there is similar code in FeatureBee.Client.
* **Authentication**: FeatureBee does not support it at all, mainly because it runs in our data center and accessible only from our network. Toguru, on another hand, designed to run in the cloud, be available from internet and so on, so getting status of toggles in not protected at all, and you have to send Authentication header with a valid API key to be able to change things, but there is no **authorisation** concept, means if you have valid API key, you can do everything. We're having some internal discussions about plugging in auth0 and add some proper permission managing, like which user is allowed to change what, etc., but it will take time until we will come to some implementation.

Hopefully that helps.
